apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeNameKSA
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodeNameKSA
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodeNameKSA
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nodeNameKSA
subjects:
- kind: ServiceAccount
  name: nodeNameKSA
