apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodenameksa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodenameksa
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodenameksa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodenameksa
subjects:
- kind: ServiceAccount
  name: nodenameksa
  namespace: nodenamelookup  
