apiVersion: v1
kind: Service
metadata:
  name: nodenamelookup
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nodenamelookup
  ports:
  - name: tcp
    protocol: TCP
    port: 8080
    targetPort: 5000
