apiVersion: v1
kind: Service
metadata:
  name: sample-v1-lb-svc
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: sample
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 80
